server:
  port: 8866

tcp:
  server:
    port: 5566

spring:
  datasource:
    url: jdbc:mysql://47.116.50.196:33060/iot
    username: root
    password: sanshao_iot
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL55Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialectdocker images
  sql:
    init:
      schema-locations: classpath:sql/oversea-schema.sql
      mode: always

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl